version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    volumes:
      - users:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'superman.cortes@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '8080:80'
    depends_on:
      - postgres
volumes:
  users:
